### ISSUE TITLE
Attemp to instantiate a class raises "TypeError: Cannot redefine property" on NodeJS 14.17.6

### ISSUE THREAD

**Issue by viktor-yunenko** [alexeyraspopov/dataclass#14]
First of all, thank you for a great package!

I wonder whether it's a misconfiguration issue, but for me the README code raises the aforementioned error:

```javascript
import Record from "dataclass";

class User extends Record {
  name = 'Anonymous';
}

let user = new User({ name: 'Liza' });
```

Eg when executed as a standalone file, along with the following `package.json`:
```json
{
  "type": "module",
  "dependencies": {
    "dataclass": "^1.2.0"
  }
}
```

The same error is happening in Firefox.

**Comment by alexeyraspopov** [comment]
There is an unfortunate thing happened some time ago that may potentially break the existing `dataclass` implementation completely. I'm still considering options and experimenting on the implementation level to make it work again.

Basically, what happened is the fact the proposal has advanced and Babel/browsers implementation of the proposal has followed. All the way back to the beginning of this project, "class property" was basically a shorthand syntax for assigning properties in constructor:

```javascript
// source
class Example extends Record {
  prop = "value";
}

// what it means
class Example extends Record {
  constructor() {
    super()
    this.prop = "value";
  }
}
```

And this idea worked just great for `dataclass`.

However, moving forward, Babel/browser implementation started using `Object.defineProperty()`:

```javascript
class Example extends Record {
  constructor() {
    super();
    Object.defineProperty(this, 'prop', { value: "value", ... })
  }
}
```

`Record`'s constructor includes all the magic and it is invoked first. If there was no special logic inside it, anything that Record assigns to `this` would be overrode by the following subclass constructor code, meaning all the props would always have "default" values and would ignore customs (`new Example({ prop: ... })`). That's the best case scenario. What happens in your case is "use strict" mode (which is default for ES Modules): attempting to use Object.defineProperty() on a prop that was already defined by Record's constructor throws a runtime error that you mentioned.

Most likely I'll need to publish a breaking change that would involve changing the DX: instead of `new User({ name: "Liza" })` developers will need to do `User.from({ name: "Liza" })` or `User.create({ name: "Liza" })` or something similar. This will help avoid the limitation described above. This should also help fixing TypeScript generic issue (mentioned in README).

**Comment by alexeyraspopov** [comment]
To summarize, this issue has been tackled as a part of the new major release `v2.0.0`. It has breaking changes that I described above. The initial example now should look like this:

```ts
import { Data } from "dataclass";

class User extends Data {
  name = 'Anonymous';
}

let user = User.create({ name: 'Liza' });
```

I hope you will get a chance to try the new release, please let me know if you still facing any issues.
