### ISSUE TITLE
Formal integration with yarn

### ISSUE THREAD

**Issue by mingchuno** [alexeyraspopov/dataclass#8]
I can submit a PR to add `yarn` integration formally with `yarn.lock` and update `.gitignore`

**Comment by alexeyraspopov** [comment]
The lib doesn't have dependencies other than for development, so there is no possible case where dynamic range of versions may break the lib because of some NPM update. Is there any other reason we may need `yarn.lock` in the project? It may lock development side of the project to the particular package manager.

**Comment by mingchuno** [comment]
true, issue close
